# Generated by Django 4.2.3 on 2023-07-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_info_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RemoveField(
            model_name='info',
            name='photo',
        ),
        migrations.AddField(
            model_name='info',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
