# Generated by Django 4.2.3 on 2023-07-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_info_options_remove_info_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='description_photo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
