# Generated by Django 4.2.3 on 2023-07-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_info_description_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='description_photo2',
            field=models.TextField(default=12312),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='description_photo3',
            field=models.TextField(default=87),
            preserve_default=False,
        ),
    ]
