# Generated by Django 4.2.3 on 2023-07-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_info_description_photo2_info_description_photo3'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='description_photo4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='description_photo5',
            field=models.TextField(default=784554),
            preserve_default=False,
        ),
    ]
