# Generated by Django 4.1.3 on 2023-07-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_info_photo_alter_info_photo2_alter_info_photo3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ФИО')),
                ('price', models.IntegerField(verbose_name='Номер')),
                ('EMail', models.TextField(verbose_name='Email')),
                ('description', models.TextField(verbose_name='Комментарий к заказу')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='photo2',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='photo3',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='photo4',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='photo5',
            field=models.CharField(max_length=300),
        ),
    ]
